/*
Serenity - The next evolution of web server technology

Copyright © 2006-2007 Serenity Project (http://SerenityProject.net/)

This file is protected by the terms and conditions of the
Microsoft Community License (Ms-CL), a copy of which should
have been distributed along with this software. If not,
you may find the license information at the following URL:

http://www.microsoft.com/resources/sharedsource/licensingbasics/communitylicense.mspx
*/
using System;
using System.Collections.Generic;
using System.Text;

namespace Serenity.Web.Drivers
{
    /// <summary>
    /// Represents a collection of options used to initialize a WebDriver with.
    /// </summary>
    public sealed class WebDriverSettings
    {
        #region Fields - Private
		private ContextHandler contextHandler;
        private IEnumerable<ushort> ports;
        #endregion
        #region Properties - Public
        /// <summary>
        /// Gets or sets a list of port numbers that should be used,
        /// in the event that the primary listen port is already in use.
        /// </summary>
        public IEnumerable<ushort> Ports
        {
            get
            {
                return this.ports;
            }
            set
            {
                this.ports = value;
            }
        }
		/// <summary>
		/// Gets or sets the ContextHandler used to process CommonContext objects generated by a WebDriver.
		/// </summary>
		public ContextHandler ContextHandler
		{
			get
			{
				return this.contextHandler;
			}
			set
			{
				this.contextHandler = value;
			}
		}
        #endregion
    }
}