//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serenity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system")]
        public string DefaultModule {
            get {
                return ((string)(this["DefaultModule"]));
            }
            set {
                this["DefaultModule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system")]
        public string DefaultTheme {
            get {
                return ((string)(this["DefaultTheme"]));
            }
            set {
                this["DefaultTheme"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public System.Boolean UseUserProfile
        {
            get {
                return ((System.Boolean)(this["UseUserProfile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("system")]
        public string DefaultEnvironment {
            get {
                return ((string)(this["DefaultEnvironment"]));
            }
            set {
                this["DefaultEnvironment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ActiveEnvironments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActiveEnvironments"]));
            }
            set {
                this["ActiveEnvironments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ActiveModules {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActiveModules"]));
            }
            set {
                this["ActiveModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ActiveThemes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActiveThemes"]));
            }
            set {
                this["ActiveThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection InactiveEnvrionments {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InactiveEnvrionments"]));
            }
            set {
                this["InactiveEnvrionments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection InactiveModules {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InactiveModules"]));
            }
            set {
                this["InactiveModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection InactiveThemes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InactiveThemes"]));
            }
            set {
                this["InactiveThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("static")]
        public string DefaultResourceClass {
            get {
                return ((string)(this["DefaultResourceClass"]));
            }
            set {
                this["DefaultResourceClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public System.Boolean OmitEnvironment {
            get {
                return ((System.Boolean)(this["OmitEnvironment"]));
            }
            set {
                this["OmitEnvironment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public System.Boolean OmitResourceClass
        {
            get {
                return ((System.Boolean)(this["OmitResourceClass"]));
            }
            set {
                this["OmitResourceClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default.html")]
        public string DefaultResourceName {
            get {
                return ((string)(this["DefaultResourceName"]));
            }
            set {
                this["DefaultResourceName"] = value;
            }
        }
    }
}
